### ISSUE TITLE
Can not connect the server with Outline client v1.3.1 windows edition

### ISSUE THREAD

**Issue by AiprNick** [Jigsaw-Code/outline-client#723]
In win10 64 bit environment, it will fail to connect the server installed in Digital Ocean.
And, it is the same when I install without anti-virus and firewall as well.

**To Reproduce**

1. Download an Outline Windows Installer from the official outline website.
2. Run with the administrator's permission to install.

**Expected behavior**
Clicking "Connect" button after 10 sec. will get the message says, "It seems like your access key is not valid. If this happens again, please contact your server admin."

**Screenshots**
![image](https://user-images.githubusercontent.com/4496011/72027607-a6163300-32ba-11ea-94e6-ecc17cf4fe2f.png)

**Desktop:**
 - OS: windows 10 home 1909
 - Browser Chrome
 - Version Version 79 (Official Build) (64-bit)

**Additional context**
However, this issue is only met in windows, I use MAC and smartphone installed outline client are Okay.

![image](https://user-images.githubusercontent.com/4496011/72027898-99460f00-32bb-11ea-9e46-7f84c7ca0b34.png)

**Smartphone:**
 - Device: HTC U11
 - OS: Android 9
 - Browser chrome
 - Version 79.0.3945.93

 **MAC book**
 - Device: MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
 - OS: macOS Catalina version 10.15.2
 - Browser chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by FEMC** [comment]
Same issue here. Then I download the v1.3 version, it works well in my Win 10 until it auto update to v1.3.1 and fail to connect again.

**Comment by AiprNick** [comment]
Is there any update?

**Comment by horyu1234** [comment]
Same issue here

**Comment by theerfan** [comment]
Same issue here, is there going to be an update?

**Comment by FEMC** [comment]
> 
> 
> Is there any update?

I downloaded the latest beta release, it seems the issue was fixed.

**Comment by AiprNick** [comment]
@FEMC Thanks! But, the v1.3.2 still does not work ...
I met the new error message like below:

![Screen Shot 2020-02-03 at 3 13 25 PM](https://user-images.githubusercontent.com/4496011/73633056-a37be300-4698-11ea-834f-43eb6e681a62.png)

The test environment is the same as before, and I purge old client including the tap device when re-installing. Of course, I also turned off the firewall and antivirus software during the installation.

**Comment by AiprNick** [comment]
It is similar to #724 issue two.

**Comment by salarx** [comment]
I'd like to confirm this issue. My i-pad, my android phone, both work fine with the access keys. But the windows pc shows the above error "an unexpected error occurred". I've tried resetting my network, restarting it, removing TAP adapter, removing openvpn connect, everything. Nothing seems to be working.

**Comment by DevHossamAli** [comment]
one of the following could be a potential solution..
- disable and enabled hyper-v
- add a fake vm in hyper-v and remove it then restart
- disable any existing bridge adapter from your network connections and try
