### ISSUE TITLE
can't install outline at windows 7  TAP device could not be installed

### ISSUE THREAD

**Issue by wecloud2008** [Jigsaw-Code/outline-client#761]
sorry,we could not configure system to connect to outline.please try running the installer again.
if you still cannot install outline,please get in touch with us and let us know that the TAP device could not be installed

**Comment by my6jay30** [comment]
> sorry,we could not configure system to connect to outline.please try running the installer again.
> if you still cannot install outline,please get in touch with us and let us know that the TAP device could not be installed

You can try to use Outline-Client version 1.2.32, it works for me

**Comment by wecloud2008** [comment]
hello 

I just now install the correct version but stall messagebox same error message

pleaes advise it

thank you

**Comment by JonathanDCohen** [comment]
@wecloud2008 this is an ongoing issue which we're working hard at to fix.  This can sometimes also happen if other VPNs are installed on the machine.

**Comment by wecloud2008** [comment]
> @wecloud2008 this is an ongoing issue which we're working hard at to fix. This can sometimes also happen if other VPNs are installed on the machine.

Thank you for your reply.

I will waiting the issue reslove.

**Comment by JonathanDCohen** [comment]
@wecloud2008 we released a new version of the Windows client yesterday, try getting a fresh download of the client and see if that works for you?  We don't think this is the final solution but hopefully it's a step forward.

**Comment by ymn** [comment]
I am still having this problem on windows 10. It was working two weeks ago now i am getting TAP error when trying to install the client. Is there any way we can reset all TAP device settings or are there any manuel steps we can take to bypass this issue?

**Comment by wecloud2008** [comment]
> @wecloud2008 we released a new version of the Windows client yesterday, try getting a fresh download of the client and see if that works for you? We don't think this is the final solution but hopefully it's a step forward.

I just now install the newer version ,but still display same error do you need debug at my computer or morn information?

version url
https://github.com/Jigsaw-Code/outline-client/releases/tag/daily-2020-03-18

**Comment by ymn** [comment]
Since i am using this on my second laptop, I used Windows's "Settings -> Recovery" option to reset the laptop. Now it works. But it will delete some of your apps. So it might not be an option for everybody. 
Looking forward for a reliable solution on this...

**Comment by JonathanDCohen** [comment]
@ymn @wecloud2008 if you email Support@getoutline.org you can get some instructions about removing the tap drivers and other support

**Comment by wecloud2008** [comment]
> @ymn @wecloud2008 if you email [Support@getoutline.org](mailto:Support@getoutline.org) you can get some instructions about removing the tap drivers and other support
> 
> This is from our support person:
> 
> TAP-Windows Adapter V9 is a network driver that allows VPN to connect to its servers. The default installation location is C:/Program Files/Tap-Windows, and it appears in Device Manager under Network Adapters category. Unfortunately, some users reported that they have connection problems when TAP Windows Adapter V9 is enabled, and even if the device is disabled, it does enable itself after a reboot of the computer.
> If you are having problems with the TAP adapter we suggest to first restart it the following way:
> In the taskbar search box, type in Control Panel
> Then go to Network and Internet Network sharing Center
> On the right side of the window, click on Change adapter settings
> Right-click on the local area connection which is using TAP Windows Adapter V9 and select Disable
> Wait a few moments, right-click it again and pick Enable
> Right-click on the Start button and select Device Manager
> Under Network adapters select TAP-Windows Adapter V9
> Right-click on it and press Uninstall device
> Follow the on-screen instructions until the process is finished
> If you cannot connect to the internet while using the VPN, try re-installing the TAP Windows Adapter V9:
> Under Network adapters select TAP-Windows Adapter V9
> Right-click on it and press Uninstall device
> Follow the on-screen instructions until the process is finished
> 
> Note: You may have to temporarily disable any Antivirus or other real-time threat monitoring software you may have on your machine.

Issue still not resolve?

**Comment by JonathanDCohen** [comment]
I'm sorry that didn't work.  This is an open issue that we've been working tirelessly to fix.  The issue is that `netsh` isn't able to find our device, even after we wait a while for it to show up on the interface list.  The API here is relatively annoying and hard to use, and also hard to test as we've never been able to consistently recreate this error on any of our Windows machines.

**Comment by ymn** [comment]
I just want to mention, that this new update does actually fix the problem of renaming the TAP adapter. I have tested it on 2 windows machines, the version before this update, there is sometimes the issue with script not able to rename tap to "outline-tap0", this new script does fix that. I was able to fix it with pulling the new add_tap_device.bat and find_tap_device_name.bat, and build&reinstall.
My problem 1 month ago, i could not even rename manually the adapter, so i think that problem was something different, fixed it by reinstalling whole windows.

**Comment by jessmanim** [comment]
Hi, I am also having the issue. Have tried the steps listed on the troubleshooting page but am still not able to install the Outinline / TAP device

**Comment by sanvit** [comment]
This seems to happen if you already have TAP driver installed by other software (it was OpenVPN GUI for me).
Deleting ALL TAP drivers on Device manager (Device manager > Network Adapters > TAP-Windows Adapter V9) and re installing Outline fixed the issue for me.

**Comment by fortuna** [comment]
@wecloud2008 is this still an issue?

**Comment by mecitorta** [comment]
ı have same problem for windows 10 too , same error.

**Comment by lgg** [comment]
@mecitorta please, can you provide app version, screenshots and logs?

**Comment by mecitorta** [comment]
> @mecitorta please, can you provide app version, screenshots and logs?

1.2.x all tried, 1.3.x all tried. non of these are working for me.
i also tried all these solution on this link ; https://github.com/Jigsaw-Code/outline-client/issues/524
![1](https://user-images.githubusercontent.com/61585098/100603689-82b30700-3316-11eb-8bab-ff25fb9ac32d.PNG)
![2](https://user-images.githubusercontent.com/61585098/100603691-834b9d80-3316-11eb-85f5-8b9b2a593282.PNG)

**Comment by lgg** [comment]
> > @mecitorta please, can you provide app version, screenshots and logs?
> 
> 1.2.x all tried, 1.3.x all tried. non of these are working for me.
> i also tried all these solution on this link ; #524
> ![1](https://user-images.githubusercontent.com/61585098/100603689-82b30700-3316-11eb-8bab-ff25fb9ac32d.PNG)
> ![2](https://user-images.githubusercontent.com/61585098/100603691-834b9d80-3316-11eb-85f5-8b9b2a593282.PNG)

@fortuna what do you think?

**Comment by alexlii1971** [comment]
I got same issue on window 7 with outline-client 1.6 version

After check network configuare, I found it automatically use dns address: 1.1.1.1, 9.9.9.9

Is that might reason?

here is the screenshot:
![WechatIMG377](https://user-images.githubusercontent.com/15896194/144990762-241418a3-ecb9-4ce1-bfe4-e68a9821e270.png)

**Comment by fortuna** [comment]
We will release a new version with a new network stack written in Go that may address some of these issues.
/cc @jyyi1 for awareness

@alexlii1971 we need to specify a DNS resolver because your local ISP resolver may be censoring the results.

**Comment by alexlii1971** [comment]
If any local antivirus or firewall is working, like 360, lenovo PC security and Tencent security, outline client installation will be completed, but client will not work even if turn off them. At least, I tried a lot, but still can not fix it.

Those so-called security software are actually also working as inspection of anti VPN.And you will note that if you have a try.

**Comment by alexlii1971** [comment]
uninsall it, and reinstall the old version:

https://github.com/Jigsaw-Code/outline-client/issues/524

https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.27

this issue is related to Tap adapter. if your client does not work, mostly, the Tap adapter is not installed by some reason, like local antivirus software or some security software.
